#!/bin/bash

set -euo pipefail

dir=$(dirname "$(readlink -f "$0")")
log_dir="$dir/log"
log_file="$log_dir/cron-$(date "+%y%m%d_%H%M%S").log"
mkdir -p "$log_dir"

cd "$dir"
make download-feed parse-press-releases 2>&1 | tee -a "$log_file"
./bin/delete-old-files "$log_dir" 50 2>&1 | tee -a "$log_file"
